name: myenv310
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - ca-certificates
  - openssl
  - matplotlib
  - certifi
  - statsmodels
  - tqdm
  - arch-py
  - numba
  - pip:
      - kymatio==0.3.0
      - scatspectra==1.1
